# Rolling nightly channel pointer — auto-generated by .github/workflows/nightly.yml.
#
# This file lives on the `nightly` git ref. The hashes and version below
# match the artifacts published in the current rolling nightly release.
# This file is NOT present on `main` with real hashes — always consume via
# the `nightly` ref:
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-nightly
#
# From-source nightly (no hash needed):
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-source
{
  version = "0.9.0-nightly+2851fa4";

  artifacts = {
    "x86_64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-amd64.tar.gz";
      hash = "sha256-G1nekgxJ6iGSkoRHlpD6TwJc5zLLp60g0m1hwMrZqs4=";
    };
    "aarch64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-arm64.tar.gz";
      hash = "sha256-qS2b6rXC/rp7uH8uw3xuWFppbJthnE6H8cV93aW7utk=";
    };
  };
}
