[package]
name = "dbflux_i18n"
edition.workspace = true
publish = false
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
sys-locale = { workspace = true }
serde_yaml = { workspace = true }
